In [1]:
import autograd.numpy as np
from autograd import grad, hessian, jacobian
from scipy.optimize import minimize

In [4]:
import matplotlib.pyplot as plt
from counterfactual_functions import *
from helper import *

username='boraozaltun'

data_dict = load_obj('/Users/'+username+'/Dropbox (MIT)/Data/Trade/general_equilibrium_gravity/final_data/data_subset_20200304.pickle')

reg_2_num = load_obj('/Users/'+username+'/Dropbox (MIT)/Data/Trade/general_equilibrium_gravity/GTAP/mapping/reg_2_num.pickle')
comm_2_num = load_obj('/Users/'+username+'/Dropbox (MIT)/Data/Trade/general_equilibrium_gravity/GTAP/mapping/comm_2_num.pickle')

n = data_dict['n']
g = data_dict['g']
k = data_dict['k']

data_dict['R_hat'] = np.ones((n, g))
data_dict['R_hat'][reg_2_num['usa'],:] = 2.
# data_dict['R_hat'][reg_2_num['usa'], 3] = 2.
# data_dict['R_hat'][reg_2_num['usa'], 4] = 2.



X_0 = np.ones(n*g + n)*2


eval_F = lambda x: reduced_counterfactual(x, data_dict)
eval_f = lambda x: np.sum(reduced_counterfactual(x, data_dict)**2)


eval_grad_f = grad(eval_f)
bounds_f = [(1e-10, None) for x in range(n*g+n)]

In [5]:
for i in data_dict.keys():
    if type(data_dict[i]) not in [int, float]:
        print(i, data_dict[i][data_dict[i]<=0])

E []
Y_g []
Y_k []
D_g_old []
D_k_old []
X_g []
X_k []
D_g []
D_k []
lambda_2_g []
lambda_2_k []
lambda_g []
lambda_k []
d [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 

In [6]:
sol = minimize(eval_f, X_0, jac=eval_grad_f, method='L-BFGS-B', bounds=bounds_f, options={'maxiter':10000})

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/autograd/numpy/numpy_vjps.py:444: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return lambda g: g[idxs]


In [7]:
sol.x

array([2.03844773e+00, 1.94014603e+00, 1.85316002e+00, 1.99927242e+00,
       2.03713863e+00, 2.03572337e+00, 2.00553027e+00, 1.91327543e+00,
       1.85281551e+00, 2.01294472e+00, 2.12515049e+00, 2.06564051e+00,
       2.02772734e+00, 1.99811814e+00, 1.84986115e+00, 2.00867692e+00,
       1.88255995e+00, 1.99698186e+00, 2.03309290e+00, 2.05104651e+00,
       2.08121652e+00, 1.96110693e+00, 2.10140913e+00, 2.01418429e+00,
       1.77359339e+00, 1.81189149e+00, 1.95520736e+00, 2.09389809e+00,
       1.98385170e+00, 2.09775207e+00, 1.86514133e+00, 1.86248608e+00,
       1.81155563e+00, 1.93960746e+00, 1.98105777e+00, 1.95864161e+00,
       1.83976274e+00, 1.94507489e+00, 1.75110333e+00, 2.00231719e+00,
       2.06312389e+00, 1.74740408e+00, 2.10690496e+00, 2.08394094e+00,
       2.10818602e+00, 2.01993103e+00, 1.92091315e+00, 2.08096804e+00,
       1.71995937e+00, 1.71820395e+00, 1.72601350e+00, 1.89237096e+00,
       2.04516387e+00, 1.83002327e+00, 2.08493100e+00, 2.06151777e+00,
      

In [8]:
sol.success

True

In [9]:
sol = minimize(eval_f, X_0/2, jac=eval_grad_f, method='L-BFGS-B', bounds=bounds_f, tol=1e-9, options={'maxiter':10000})

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/autograd/numpy/numpy_vjps.py:444: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return lambda g: g[idxs]


In [10]:
sol.x

array([1.02011396e+00, 9.71711707e-01, 9.25581766e-01, 1.00313928e+00,
       1.01906445e+00, 1.01801379e+00, 1.00100841e+00, 9.56632697e-01,
       9.24786613e-01, 1.00932101e+00, 1.06179296e+00, 1.03212304e+00,
       1.01276783e+00, 9.99059734e-01, 9.23333984e-01, 1.00740305e+00,
       9.42058095e-01, 9.97048753e-01, 1.01362474e+00, 1.02607390e+00,
       1.04335088e+00, 9.84189255e-01, 1.05068317e+00, 1.00436108e+00,
       8.85284499e-01, 9.06161837e-01, 9.77119550e-01, 1.04829985e+00,
       9.92131272e-01, 1.05029111e+00, 9.24534400e-01, 9.28293096e-01,
       9.02551819e-01, 9.72026876e-01, 9.89093780e-01, 9.73182535e-01,
       9.18208283e-01, 9.72338356e-01, 8.74195738e-01, 1.00402295e+00,
       1.03155716e+00, 8.72050216e-01, 1.05294977e+00, 1.04202014e+00,
       1.05568765e+00, 1.01250388e+00, 9.60312932e-01, 1.03964278e+00,
       8.58810473e-01, 8.60005874e-01, 8.62158622e-01, 9.51076269e-01,
       1.02257225e+00, 9.14940121e-01, 1.04176387e+00, 1.03084361e+00,
      

In [20]:
## THINK ABOUT THIS TOMORROW 

In [16]:
r_hat_star, w_hat_star = get_values_from_X_reduced(sol.x, data_dict)

In [22]:
r_hat_star

array([[1.020403  , 1.02727633, 1.02650429, 0.92977971, 0.94676646,
        1.02087812],
       [1.01766118, 1.02453283, 1.02667459, 0.93373979, 1.022203  ,
        1.01326719],
       [1.02093649, 1.02412641, 1.0259528 , 0.93514672, 0.87245416,
        1.02021073],
       [1.02699731, 1.02901666, 1.0262427 , 0.91559879, 0.97860859,
        1.03097528],
       [1.01846247, 1.02915085, 1.02314681, 0.99012341, 0.92553335,
        0.99970591],
       [1.03279317, 1.03290032, 1.03109013, 0.90544209, 0.92165843,
        1.03157662],
       [1.02261903, 1.02511825, 1.02627236, 0.93593191, 0.9606459 ,
        1.01743055],
       [0.99378508, 1.01389622, 1.02041792, 0.94296019, 0.89605867,
        1.02045725],
       [1.02182234, 1.02233195, 1.02923707, 0.88839697, 0.95449875,
        1.01474723],
       [1.00838909, 1.01924743, 1.01381981, 0.92426066, 0.98755313,
        1.0179497 ],
       [0.98970108, 1.01902389, 1.02325478, 0.91797371, 0.89860046,
        0.98667199],
       [1.02128183, 1

In [16]:
w_hat_star

array([[1.01381085],
       [1.01669208],
       [1.0146282 ],
       [1.01122466],
       [1.01369828],
       [1.01067611],
       [1.01697992],
       [1.01362524],
       [1.01587333],
       [1.01551079],
       [1.01113246],
       [1.01503568],
       [1.01060958],
       [1.01752012],
       [1.02240009],
       [1.02006577],
       [1.02018655],
       [1.00591746],
       [1.00647687],
       [1.0202566 ],
       [1.01982926],
       [1.01055177],
       [1.02330052],
       [1.01908074],
       [1.01715756],
       [1.01972165],
       [1.02010894],
       [1.02762382],
       [1.01840103],
       [1.01357581],
       [1.01403421],
       [1.01653066],
       [1.01988376],
       [1.02326062],
       [1.01265166],
       [1.01218009],
       [1.01753669],
       [1.02033354],
       [1.01356641],
       [1.02033766],
       [1.02303893],
       [1.03390944],
       [1.00502697],
       [1.02681866],
       [1.01401883],
       [1.02577069],
       [1.01649409],
       [1.022

In [9]:
## Weird, it is working...