In [1]:
# I think that the 12 equations can be reduced to (2) w_hat, r_hat. Lets see!

In [1]:
from scipy.optimize import fsolve, root, newton_krylov
from scipy.optimize import minimize
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from jax import jacfwd, jacrev
from counterfactual_functions import *
from helper import *

In [2]:
data_dict = load_obj('/Users/boraozaltun/Dropbox (MIT)/Data/Trade/general_equilibrium_gravity/final_data/data_20200212.pickle')

# For stability

data_dict['phi_R'][data_dict['phi_R'] == 0 ] = 1e-14





In [3]:
reg_2_num = load_obj('/Users/boraozaltun/Dropbox (MIT)/Data/Trade/general_equilibrium_gravity/GTAP/mapping/reg_2_num.pickle')
comm_2_num = load_obj('/Users/boraozaltun/Dropbox (MIT)/Data/Trade/general_equilibrium_gravity/GTAP/mapping/comm_2_num.pickle')

In [4]:
n = data_dict['n']
g = data_dict['g']
k = data_dict['k']

data_dict['R_hat'] = np.ones((n, g))
# data_dict['R_hat'][reg_2_num['usa'], comm_2_num['oil']] = 2
# data_dict['R_hat'][reg_2_num['usa'], comm_2_num['gas']] = 2

F = lambda x: reduced_counterfactual(x, data_dict)

In [5]:
X_0 = np.ones(n*g + n)*0.5

In [2]:
# X = fsolve(F, X_0)

In [7]:
sol = minimize(F, X_0, method='L-BFGS-B', bounds=[(0.,None) for x in range(n*g+n)])

[]
[]


ValueError: The user-provided objective function must return a scalar value.

In [ ]:
sol

In [9]:
# X

In [10]:
# X = newton_krylov(F, X_0)

In [11]:
sol = root(F, X_0, method='broyden1', tol=1e-4)

[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]


/Users/boraozaltun/GitHub/fossilfuelnetworkscience/General Equilibrium Model/solver/counterfactual_functions.py:130: RuntimeWarning: invalid value encountered in power
  part1 = data['phi_R'] * (r_hat ** (1- data['rho_g'].reshape((1, data['g']))))
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scipy/optimize/nonlin.py:1004: RuntimeWarning: invalid value encountered in true_divide
  d = v / vdot(df, v)


[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15

[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0

[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0

[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15

[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0

[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15

[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0

[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15

[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15166203  -9.20669822  -0.48094374 -11.25476434]
[]
[ -0.12879897  -0.15

KeyboardInterrupt: 

In [8]:
sol

    fjac: array([[-8.67218089e-02,  0.00000000e+00,  0.00000000e+00, ...,
         3.23063913e-08,  1.61531957e-08,  3.23063913e-08],
       [ 9.76304528e-01, -1.38045204e-02,  0.00000000e+00, ...,
         5.27866593e-09, -1.66453593e-08, -1.14347340e-08],
       [ 4.40615764e-02,  5.32272784e-01, -8.23128310e-01, ...,
         1.52113193e-08,  2.29140712e-08, -1.11289528e-08],
       ...,
       [-3.37009166e-06, -2.42361011e-04, -1.57109110e-04, ...,
        -9.24981479e-01,  2.46251515e-01,  7.78013280e-02],
       [-6.58988743e-07, -4.79345460e-05, -3.11105165e-05, ...,
        -5.53232559e-02, -4.31918470e-01,  8.57983630e-01],
       [-6.49095921e-06, -4.68512951e-04, -3.03714489e-04, ...,
        -1.34766981e-02, -6.01380242e-05, -1.47969998e-01]])
     fun: array([ 0.005     ,  0.005     ,  0.005     , ..., -0.00347802,
       -0.00794864, -0.00304857])
 message: 'The iteration is not making good progress, as measured by the \n  improvement from the last ten iterations.'
    n

In [9]:
# Next thing to try: normalize all the values that need to be normalizedx

In [10]:
# It seems quite early on, something is going wrong
# Also, curious if I can speed it up in different ways 

In [8]:
# f = lambda W: reduced_counterfactual(W, data_dict)

In [10]:
# J = jacfwd(f)

In [ ]:
# J(X_0)

In [19]:
def F2(x):
    output = np.array([x[0]**2 +x[1]**2 -4, x[0]+x[1] -2])
    return output

In [20]:
fsolve(F2, np.array([1, 1]))

array([2.00000000e+00, 2.89180796e-15])